/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalCard: typeof import('./../packages/components/src/approval-card/index.vue')['default']
    Audio: typeof import('./../packages/components/src/audio/index.vue')['default']
    Badge: typeof import('./../packages/components/src/core/components/badge/index.vue')['default']
    Button: typeof import('./../packages/components/src/core/components/button/index.vue')['default']
    Card: typeof import('./../packages/components/src/core/components/card/index.vue')['default']
    CardContent: typeof import('./../packages/components/src/core/components/card/CardContent.vue')['default']
    CardDescription: typeof import('./../packages/components/src/core/components/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../packages/components/src/core/components/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../packages/components/src/core/components/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../packages/components/src/core/components/card/CardTitle.vue')['default']
    Chart: typeof import('./../packages/components/src/chart/index.vue')['default']
    Citation: typeof import('./../packages/components/src/citation/index.vue')['default']
    CitationList: typeof import('./../packages/components/src/citation/cmpts/citation-list.vue')['default']
    CodeBlock: typeof import('./../packages/components/src/code-block/index.vue')['default']
    CodeDiff: typeof import('./../packages/components/src/code-diff/index.vue')['default']
    CopyButton: typeof import('./../packages/components/src/core/components/copy-button/index.vue')['default']
    DataTable: typeof import('./../packages/components/src/data-table/index.vue')['default']
    DemoChatMessage: typeof import('./components/demo-chat-message.vue')['default']
    DemoDelayedShow: typeof import('./components/demo-delayed-show.vue')['default']
    DemoRestaurant: typeof import('./components/demo-restaurant.vue')['default']
    EffectCompositor: typeof import('./../packages/components/src/weather-widget/cmpts/effect-compositor.vue')['default']
    GalleryGrid: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-grid.vue')['default']
    GalleryImageCard: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-image-card.vue')['default']
    GalleryLightbox: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-lightbox.vue')['default']
    GeoMap: typeof import('./../packages/components/src/geo-map/index.vue')['default']
    GeoMapEngine: typeof import('./../packages/components/src/geo-map/cmpts/geo-map-engine.vue')['default']
    GeoMapOverlays: typeof import('./../packages/components/src/geo-map/cmpts/geo-map-overlays.vue')['default']
    Image: typeof import('./../packages/components/src/image/index.vue')['default']
    ImageGallery: typeof import('./../packages/components/src/image-gallery/index.vue')['default']
    InstagramPost: typeof import('./../packages/components/src/instagram-post/index.vue')['default']
    ItemCard: typeof import('./../packages/components/src/item-carousel/cmpts/item-card.vue')['default']
    ItemCarousel: typeof import('./../packages/components/src/item-carousel/index.vue')['default']
    LinkedinPost: typeof import('./../packages/components/src/linkedin-post/cmpts/linkedin-post.vue')['default']
    LinkPreview: typeof import('./../packages/components/src/link-preview/index.vue')['default']
    LocaleProvider: typeof import('./../packages/components/src/core/i18n/locale-provider/index.vue')['default']
    MessageDraft: typeof import('./../packages/components/src/message-draft/cmpts/message-draft.vue')['default']
    OptionList: typeof import('./../packages/components/src/option-list/index.vue')['default']
    OrderSummary: typeof import('./../packages/components/src/order-summary/index.vue')['default']
    ParameterSlider: typeof import('./../packages/components/src/parameter-slider/index.vue')['default']
    Plan: typeof import('./../packages/components/src/plan/index.vue')['default']
    PreferencesPanel: typeof import('./../packages/components/src/preferences-panel/index.vue')['default']
    ProgressTracker: typeof import('./../packages/components/src/progress-tracker/index.vue')['default']
    QuestionFlow: typeof import('./../packages/components/src/question-flow/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sparkline: typeof import('./../packages/components/src/stats-display/cmpts/sparkline.vue')['default']
    StatsDisplay: typeof import('./../packages/components/src/stats-display/index.vue')['default']
    Terminal: typeof import('./../packages/components/src/terminal/index.vue')['default']
    Video: typeof import('./../packages/components/src/video/index.vue')['default']
    WeatherDataOverlay: typeof import('./../packages/components/src/weather-widget/cmpts/weather-data-overlay.vue')['default']
    WeatherEffectsCanvas: typeof import('./../packages/components/src/weather-widget/cmpts/weather-effects-canvas.vue')['default']
    WeatherWidget: typeof import('./../packages/components/src/weather-widget/index.vue')['default']
    XPost: typeof import('./../packages/components/src/x-post/index.vue')['default']
  }
}
