/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalCard: typeof import('./../packages/components/src/approval-card/index.vue')['default']
    Audio: typeof import('./../packages/components/src/audio/index.vue')['default']
    Chart: typeof import('./../packages/components/src/chart/index.vue')['default']
    Citation: typeof import('./../packages/components/src/citation/index.vue')['default']
    CitationList: typeof import('./../packages/components/src/citation/cmpts/citation-list.vue')['default']
    CodeBlock: typeof import('./../packages/components/src/code-block/index.vue')['default']
    CodeDiff: typeof import('./../packages/components/src/code-diff/index.vue')['default']
    DataTable: typeof import('./../packages/components/src/data-table/index.vue')['default']
    EffectCompositor: typeof import('./../packages/components/src/weather-widget/cmpts/effect-compositor.vue')['default']
    GalleryGrid: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-grid.vue')['default']
    GalleryImageCard: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-image-card.vue')['default']
    GalleryLightbox: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-lightbox.vue')['default']
    GeoMap: typeof import('./../packages/components/src/geo-map/index.vue')['default']
    GeoMapEngine: typeof import('./../packages/components/src/geo-map/cmpts/geo-map-engine.vue')['default']
    GeoMapOverlays: typeof import('./../packages/components/src/geo-map/cmpts/geo-map-overlays.vue')['default']
    Image: typeof import('./../packages/components/src/image/index.vue')['default']
    ImageGallery: typeof import('./../packages/components/src/image-gallery/index.vue')['default']
    InstagramPost: typeof import('./../packages/components/src/instagram-post/index.vue')['default']
    ItemCard: typeof import('./../packages/components/src/item-carousel/cmpts/item-card.vue')['default']
    ItemCarousel: typeof import('./../packages/components/src/item-carousel/index.vue')['default']
    LinkedinPost: typeof import('./../packages/components/src/linkedin-post/cmpts/linkedin-post.vue')['default']
    LinkPreview: typeof import('./../packages/components/src/link-preview/index.vue')['default']
    MessageDraft: typeof import('./../packages/components/src/message-draft/cmpts/message-draft.vue')['default']
    OptionList: typeof import('./../packages/components/src/option-list/index.vue')['default']
    OrderSummary: typeof import('./../packages/components/src/order-summary/index.vue')['default']
    ParameterSlider: typeof import('./../packages/components/src/parameter-slider/index.vue')['default']
    Plan: typeof import('./../packages/components/src/plan/index.vue')['default']
    PreferencesPanel: typeof import('./../packages/components/src/preferences-panel/index.vue')['default']
    ProgressTracker: typeof import('./../packages/components/src/progress-tracker/index.vue')['default']
    QuestionFlow: typeof import('./../packages/components/src/question-flow/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sparkline: typeof import('./../packages/components/src/stats-display/cmpts/sparkline.vue')['default']
    StatsDisplay: typeof import('./../packages/components/src/stats-display/index.vue')['default']
    Terminal: typeof import('./../packages/components/src/terminal/index.vue')['default']
    Video: typeof import('./../packages/components/src/video/index.vue')['default']
    WeatherDataOverlay: typeof import('./../packages/components/src/weather-widget/cmpts/weather-data-overlay.vue')['default']
    WeatherEffectsCanvas: typeof import('./../packages/components/src/weather-widget/cmpts/weather-effects-canvas.vue')['default']
    WeatherWidget: typeof import('./../packages/components/src/weather-widget/index.vue')['default']
    XPost: typeof import('./../packages/components/src/x-post/index.vue')['default']
  }
}

// For TSX support
declare global {
  const ApprovalCard: typeof import('./../packages/components/src/approval-card/index.vue')['default']
  const Audio: typeof import('./../packages/components/src/audio/index.vue')['default']
  const Chart: typeof import('./../packages/components/src/chart/index.vue')['default']
  const Citation: typeof import('./../packages/components/src/citation/index.vue')['default']
  const CitationList: typeof import('./../packages/components/src/citation/cmpts/citation-list.vue')['default']
  const CodeBlock: typeof import('./../packages/components/src/code-block/index.vue')['default']
  const CodeDiff: typeof import('./../packages/components/src/code-diff/index.vue')['default']
  const DataTable: typeof import('./../packages/components/src/data-table/index.vue')['default']
  const EffectCompositor: typeof import('./../packages/components/src/weather-widget/cmpts/effect-compositor.vue')['default']
  const GalleryGrid: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-grid.vue')['default']
  const GalleryImageCard: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-image-card.vue')['default']
  const GalleryLightbox: typeof import('./../packages/components/src/image-gallery/cmpts/gallery-lightbox.vue')['default']
  const GeoMap: typeof import('./../packages/components/src/geo-map/index.vue')['default']
  const GeoMapEngine: typeof import('./../packages/components/src/geo-map/cmpts/geo-map-engine.vue')['default']
  const GeoMapOverlays: typeof import('./../packages/components/src/geo-map/cmpts/geo-map-overlays.vue')['default']
  const Image: typeof import('./../packages/components/src/image/index.vue')['default']
  const ImageGallery: typeof import('./../packages/components/src/image-gallery/index.vue')['default']
  const InstagramPost: typeof import('./../packages/components/src/instagram-post/index.vue')['default']
  const ItemCard: typeof import('./../packages/components/src/item-carousel/cmpts/item-card.vue')['default']
  const ItemCarousel: typeof import('./../packages/components/src/item-carousel/index.vue')['default']
  const LinkedinPost: typeof import('./../packages/components/src/linkedin-post/cmpts/linkedin-post.vue')['default']
  const LinkPreview: typeof import('./../packages/components/src/link-preview/index.vue')['default']
  const MessageDraft: typeof import('./../packages/components/src/message-draft/cmpts/message-draft.vue')['default']
  const OptionList: typeof import('./../packages/components/src/option-list/index.vue')['default']
  const OrderSummary: typeof import('./../packages/components/src/order-summary/index.vue')['default']
  const ParameterSlider: typeof import('./../packages/components/src/parameter-slider/index.vue')['default']
  const Plan: typeof import('./../packages/components/src/plan/index.vue')['default']
  const PreferencesPanel: typeof import('./../packages/components/src/preferences-panel/index.vue')['default']
  const ProgressTracker: typeof import('./../packages/components/src/progress-tracker/index.vue')['default']
  const QuestionFlow: typeof import('./../packages/components/src/question-flow/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Sparkline: typeof import('./../packages/components/src/stats-display/cmpts/sparkline.vue')['default']
  const StatsDisplay: typeof import('./../packages/components/src/stats-display/index.vue')['default']
  const Terminal: typeof import('./../packages/components/src/terminal/index.vue')['default']
  const Video: typeof import('./../packages/components/src/video/index.vue')['default']
  const WeatherDataOverlay: typeof import('./../packages/components/src/weather-widget/cmpts/weather-data-overlay.vue')['default']
  const WeatherEffectsCanvas: typeof import('./../packages/components/src/weather-widget/cmpts/weather-effects-canvas.vue')['default']
  const WeatherWidget: typeof import('./../packages/components/src/weather-widget/index.vue')['default']
  const XPost: typeof import('./../packages/components/src/x-post/index.vue')['default']
}